### ISSUE TITLE
Send message with different username

### ISSUE THREAD

**Issue by tedkozma** [regisb/slack-cli#8] opened 2018-12-05 21:38 UTC
Is there any possibility to get a behaviour similar to this other slack CLI-tool (https://www.npmjs.com/package/slack-cli), where a message can be sent with a different username ?

**Comment by regisb** [comment] 2018-12-06 08:22
Hi! Yes, it's possible. The message will appear as coming from a bot with the chosen name, like this:

![depressed](https://user-images.githubusercontent.com/44319/49570999-6010d200-f938-11e8-8398-88d4e1a2ae19.png)

What's your use case?

**Comment by tedkozma** [comment] 2018-12-08 16:54
thanks, @regisb, it's a useful feature!

**Comment by tedmiston** [comment] 2020-01-29 21:36
Any idea if this feature still works?  When I try passing `-u foo` or `--username foo`, the message doesn't send and silently errors out.

When I omit this arg it works as expected.

**Comment by regisb** [comment] 2020-02-03 10:23
@tedmiston Thanks for reporting this. Indeed, I managed to reproduce the issue. However, I have no idea why the message is not properly sent: the response from the Slack API includes an "ok":

    $ slack-cli -d thetestbot -u somerandomuser "hello"
    ...
    '{"ok":true,"channel":"D3BN06XU1","ts":"1580724803.000200","message":{"type":"message","subtype":"bot_message","text":"hello","ts":"1580724803.000200","username":"somerandomuser","bot_id":"B70GTBUBD"}}'

Thus, I believe this is an upstream bug in the Slack API :-/ 
For reference, here is the relevant section of the documentation: https://api.slack.com/methods/chat.postMessage#authorship

I'll reopen this issue.

**Comment by tedmiston** [comment] 2020-02-03 15:35
Glad to hear that you can reproduce.

I looked all over the Slack docs for mention of the `as_user` feature being officially removed but I didn't find anything.  The legacy tokens are deprecated of course (https://api.slack.com/legacy/custom-integrations/legacy-tokens) but as far as I can tell none of the functionality has been intentionally disabled by Slack.

Curiously, I tried to reproduce this again today and it seems to be working for me now.

This is what I called:

```
$ slack-cli -T myteam -d my.user -u foo 'test'
```

**Comment by regisb** [comment] 2020-02-03 17:26
> Curiously, I tried to reproduce this again today and it seems to be working for me now.

Right! I understand what's going on now. It's not possible to view the personal message sent from user X to user Y if you are not either X or Y. But if you use the `-u` option to send a message to yourself or to a channel, then you'll see the message appear. Thus, the feature works as expected and I can close this.

**Closed by regisb** 2020-02-03 17:26 UTC

**Comment by tedmiston** [comment] 2020-02-04 00:49
Ahh okay.  So it is not really possible to use the `-u` option to send a message to a channel from User A (with code run by User B) and then have all users of that channel see it?

**Comment by regisb** [comment] 2020-02-04 08:15
> Ahh okay. So it is not really possible to use the -u option to send a message to a channel from User A (with code run by User B) and then have all users of that channel see it?

Yes it is. What is not possible is to send a private message from user A to user C.

**Comment by tedmiston** [comment] 2020-02-04 16:12
That makes sense.  So maybe there is a bug here after all.  When I commented on the issue initially, I was sending the message to Slackbot.

```
$ slack-cli -T myteam -d Slackbot -u Foo 'test'
Channel, group or user 'Slackbot' does not exist

$ slack-cli -T myteam -d slackbot -u Foo 'test'
```

The latter call still does not work for me (errors out silently and message does not show up).

It sounds like the API call may be intentionally not supported if Slackbot is considered a user.  But perhaps there is a bug that `slack-cli` does not return an error for the latter (which could potentially be due to an underlying Slack API bug)?

**Comment by regisb** [comment] 2020-02-04 16:16
Slackbot *is* considered as a user. I made sure of that by checking the API response (which I pasted in my above comment https://github.com/regisb/slack-cli/issues/8#issuecomment-581341041)
