### ISSUE TITLE
piping from cat to slack-cli -d sends each line separately instead of all as one block

### ISSUE THREAD

**Issue by wsturgiss** [regisb/slack-cli#12] opened 2018-12-19 18:18 UTC

**Comment by wsturgiss** [comment] 2018-12-19 18:19
the command I am using is 
`cat filename.txt | slack-cli -d username`
and it sends each line separately.  Is this the intended functionality and I just need to find a way to send it in as a block?  It seems like its not the intended functionality.

**Comment by regisb** [comment] 2018-12-19 22:20
I'm afraid this is the intended behaviour... Let me explain: the "pipe" feature was designed with the `tail -f` scenario in mind:

    tail -f nginx/access.log | slack-cli -d devteam

In this scenario, we never reach the end of the file. We need each line to be printed one at a time. And while reading from standard input, there is no way for slack-cli to guess that the input is going to reach an end, sooner or later.

Do you see the problem?

Do not despair, though :) You can achieve exactly what you need with: 

    slack-cli -d username "$(cat filename.txt)"

or:

    slack-cli -d username --pre "$(cat filename.txt)"

Since this solution solves the problem at hand, I'll close this issue now. Feel free to reopen if you feel it does not fully address your problem.

**Closed by regisb** 2018-12-19 22:20 UTC

**Comment by wsturgiss** [comment] 2018-12-20 15:17
This works well, but it seems that if the file is long enough, it gets split into two parts.  3978 characters or less works fine, but if you go beyond that it is split in two, and one message gets the opening ``` and the other gets the closing ``` causing neither to be a code block. 

This seems to be a limitation in the native app as well.  If you paste something into the message box longer than 3978 characters it prompts you to create a snippet out of it instead. 

Other than this limitation, this solution works fine.  I had a feeling it would involve some bash voodoo but wasn't able to figure exactly how to do it.  Thanks for offering this solution, it will work just fine.

A future feature request would be the ability to create snippets in the CLI.  I can create that as a separate issue since it doesn't seem to be related to this.
